### ISSUE TITLE
Join request

### ISSUE THREAD

**Issue by Xd-pro** [Repl-it-Coders/ReplitNames#2]
Can I join? My username on replit is [xfinnbar](https://replit.com/@xfinnbar), and you'll probably see me on talk answering questions or releasing projects and utilities sometimes.

**Comment by keystove** [comment]
Well @Xd-pro, I'm just a member so I can't let you in but I can ping the people who could ;). @whippingdot @JBYT27 @darkdarcool

**Comment by JBYT27** [comment]
Hi there @Xd-pro!

I can let you in *with* @whippingdot’s permission. They’re the organization leader, so yeah.

I’ll let you know when ur in or when I get whippingdot’s perm.

**Comment by keystove** [comment]
*yess*

**Comment by whippingdot** [comment]
I want to say we don't have a leader because technoblade and anarchy so from now on I trust the mods to look into people's accounts and invite them to the organization

**Comment by darkdarcool** [comment]
Hi @Xd-pro, we have a lot of members, which I think we have a good amount, but can you leave a list of all of the Lang’s you know and a _good_ project to go with the lang that’s made in said lang, and if I like the projects, I’ll inv you to the org!

**Comment by whippingdot** [comment]
??? You know if I didn't create the org and tried to come in and you said this to me I would've never made it into the org so...

**Comment by darkdarcool** [comment]
Ik, but I think we have enough too many members, and it get chaotic, but I’m fine with letting him in

**Comment by whippingdot** [comment]
lol i want a load of members. BTW half the people who join don't respond so I don't think it is 'chaotic'. I don't want to through your choices to the side though so you can choose

**Comment by darkdarcool** [comment]
k, but as long as he provides the lang's he knows (ya did that to me when i joined)

**Comment by Xd-pro** [comment]
I have most experience with Python and frontend JavaScript, but I also know decent Java and basic Rust and C#. I've got ~120 cycles

**Comment by darkdarcool** [comment]
Nice, I'll let you in!

**Comment by RayhanADev** [comment]
@Xd-pro oh hey I know you

@darkdarcool yeah it's fine.

**Comment by whippingdot** [comment]
Yeah i am cool

**Comment by keystove** [comment]
> i am cool

🕶

**Comment by JBYT27** [comment]
Its fine, sry for late comment

**Comment by darkdarcool** [comment]
It’s fine

**Comment by whippingdot** [comment]
@Xd-pro has died

**Comment by keystove** [comment]
rip
