### ISSUE TITLE
Find the mistake

### ISSUE THREAD

**Issue by whippingdot** [Repl-it-Coders/ReplitNames#3]
Bro is github glitched or did Tr1ngular break the repo
![image](https://user-images.githubusercontent.com/64354499/127270196-ebaf3a58-9522-417f-aa22-9e94f4d1b5d9.png)

Find the mistake in this picture 🤦

**Comment by keystove** [comment]
the 1 month old? i dont have that. and why is there no releases header of the 1 tags? WHY IS FOREEROSANTIAGO'S PROFILE WEIRD? SO MANY THINGS ARE WRONG! i think it is ur problem @whippingdot. mine looks *chill*.

**Comment by keystove** [comment]
![image](https://user-images.githubusercontent.com/79815764/127361222-65314cce-eb55-4ac1-aa95-47e913fe4f45.png)

**Comment by keystove** [comment]
that is how mine looks

**Comment by keystove** [comment]
and also did you know that i was the one that made this repo in my account, then transferred it to the org.

**Comment by keystove** [comment]
and yet i am the person who almost has the LEAST NUMBER OF CONTRIBUTIONS???

**Comment by whippingdot** [comment]
lol... who are you? Also I have an extension...it must be broken. I shall update it now (there is an update pending)

**Comment by keystove** [comment]
what. you don't know me. >:|

**Comment by whippingdot** [comment]
Nope...

**Comment by keystove** [comment]
firefish111 literally said i was thequackyduck (or iop3, or icinghackz) in disguise

**Comment by whippingdot** [comment]
then who is @theiocoder

**Comment by keystove** [comment]
bru, he told you. he was CodingRedPanda (i think)

**Comment by whippingdot** [comment]
oh ok... ridark

**Comment by whippingdot** [comment]
brah github org ded

**Comment by keystove** [comment]
ikr
