### ISSUE TITLE
Can I join y'all?  

### ISSUE THREAD

**Issue by Conner1115** [Repl-it-Coders/ReplitNames#4]
Yo guys it's me LeviathanCoding.  Ya mind if I join the org?

**Comment by Conner1115** [comment]
I might help y'all out after the replit Kajam competition.

**Comment by YEETEDWIN** [comment]
I am still here, I guess it did die. But don't take me out

**Comment by iop3** [comment]
i'm still here too. welp, closing.

**Comment by whippingdot** [comment]
hey @Conner1115 bro you free now? We can revive the org if you are

**Comment by Conner1115** [comment]
I'll be free tomorrow.  I have a job interview with Faris Masad at replit
today.

**Comment by whippingdot** [comment]
WOAHHH

**Comment by sn236** [comment]
@whippingdot can I join if this org is still there

**Comment by whippingdot** [comment]
@Conner1115 you free on the 10th (sorry for disturbing you)

If you are not its okay ima just redo everything myself and you can join afterwards.

**Comment by Conner1115** [comment]
I don't exactly know, but I should be free on the 10th of december.
